apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ysqitg0u3-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:b3781f2f8fbf852fe7b62dd2008a9b60ac71c808@sha256:3271ab23248e037dc94edd274b4c8ca7eb8fdeed0b79ba89368d690f3d4eb785
          name: container-image
