apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ysqitg0u3-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:35204eeb0dc3b063cfc887e25e50bcb384c45d9c@sha256:41d32551b61af7bcfd0f3d0baf89772199da519c3b5f070894128b39321b3bb4
          name: container-image
